# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 071f90afaf5184d2d4d76b05c776fe623b1a7a20f41cb9984ff06255b85784ceb8c768b37fc0b3286ed80c9a5525b1231665a0538288ff8c1d8f547076fbe121

test:
  secret_key_base: d9331995599e5204b6cf15dcace71fce42a3abf0aa446436859130585f7fab2350f62b645c4d60fc9563ad5fc98ce3b33c46c1a7b193a01eecb93da3b6cba2c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
